

class names_espadas:

    def Espadas(self):
        nomes = [ "Lâmina do Dragão",
    "Cortadora Celestial",
    "Espada da Noite Eterna",
    "Fúria de Fogo",
    "Lâmina do Destino",
    "Tempestade de Aço",
    "Espada da Luz Divina",
    "Cortadora das Sombras",
    "Guardiã das Estrelas",
    "Lâmina dos Ventos",
    "Espada da Fênix",
    "Golpe Imortal",
    "Fúria do Oceano",
    "Lâmina dos Céus",
    "Espada da Aurora",
    "Sangue de Ferro",
    "Cortadora de Almas",
    "Lâmina Espectral",
    "Espada do Vazio",
    "Chama Infinita",
    "Coração de Gelo",
    "Espada do Caos",
    "Golpe Fantasma",
    "Lâmina da Justiça",
    "Espada do Leão",
    "Cortadora de Fogo",
    "Fúria das Estrelas",
    "Espada da Eternidade",
    "Lâmina das Sombras",
    "Espada da Tempestade",
    "Guardião do Trono",
    "Espada do Relâmpago",
    "Lâmina dos Deuses",
    "Espada do Vento Norte",
    "Coração de Aço",
    "Espada da Morte",
    "Cortadora de Raios",
    "Fúria dos Mares",
    "Lâmina de Prata",
    "Espada da Paz",
    "Guardião da Noite",
    "Espada do Sol",
    "Cortadora do Inferno",
    "Espada da Lua",
    "Golpe do Trovão",
    "Lâmina da Fênix",
    "Espada do Guardião",
    "Coração de Cristal",
    "Espada da Tormenta",
    "Lâmina do Amanhecer",
    "Espada do Lobo",
    "Cortadora de Neve",
    "Fúria do Vulcão",
    "Espada da Justiça",
    "Lâmina de Sangue",
    "Espada do Crepúsculo",
    "Guardião do Fogo",
    "Espada do Gelo",
    "Cortadora de Sombras",
    "Espada da Redenção",
    "Lâmina das Chamas",
    "Espada do Céu",
    "Coração de Ouro",
    "Espada do Guerreiro",
    "Cortadora de Ossos",
    "Espada da Esperança",
    "Fúria do Deserto",
    "Espada da Vingança",
    "Lâmina do Caçador",
    "Espada do Rei",
    "Golpe do Dragão",
    "Lâmina do Destino",
    "Espada do Panteão",
    "Cortadora de Ferro",
    "Espada da Vitória",
    "Guardião da Morte",
    "Espada do Guardião",
    "Lâmina da Verdade",
    "Espada da Chama",
    "Cortadora de Vento",
    "Espada do Silêncio",
    "Fúria do Guerreiro",
    "Espada da Sombra",
    "Lâmina dos Anjos",
    "Espada do Guardião",
    "Coração de Fogo",
    "Espada do Deus Sol",
    "Golpe do Destino",
    "Lâmina do Guerreiro",
    "Espada do Leão",
    "Cortadora do Céu",
    "Espada do Cavaleiro",
    "Fúria do Trovão",
    "Espada do Dragão",
    "Lâmina da Tempestade",
    "Espada da Alma",
    "Coração de Fogo",
    "Espada da Luz",
    "Lâmina do Guardião"]
        return nomes